

compile :
	g++ SortTest.cpp -std=c++11 -o Main

MergeSort :
	./Main MergeSort

QuickSort :
	./Main QuickSort

HeapSort :
	./Main HeapSort

LinkedList :
	./Main LinkedList

all : compile MergeSort QuickSort HeapSort clean


clean :
	rm -rf Main
