
all : compile 

compile :
	g++ -std=c++11 BSTTest.cc -o Main

naive :
	./Main naive

silent :
	./Main silent 10

silent_1000 : 
	./Main silent 1000

silent_10000:
	./Main silent 10000

silent_100000 :
	./Main silent 100000

silent_1000000 :
	./Main silent 1000000

clean :
	rm -rf Main
